"""Dossier generation.

Always produces a readable markdown dossier from templates. If the
`anthropic` package is installed and an API key is available, Claude
writes the full analyst version on top of the same facts. Without a
key, the template version stands on its own — the demo must never
require credentials.
"""

from __future__ import annotations

import dataclasses
import json
import os

import yaml

from succession_radar.adapters.base import Company
from succession_radar.agent.prompts import DOSSIER_REQUEST, SYSTEM_PROMPT
from succession_radar.matching.matcher import BuyerMatch, load_knowledge, match_buyers
from succession_radar.scoring.engine import ScoreReport

DEFAULT_MODEL = os.environ.get("RADAR_LLM_MODEL", "claude-opus-5")


def _seller_notes(limit: int = 4) -> list[str]:
    """The seller-protection points from the knowledge base."""
    try:
        checklist = load_knowledge()["seller_economics"]["seller_protection_checklist"]
    except (KeyError, TypeError):
        return []
    return [" ".join(item.split()) for item in checklist[:limit]]


def template_dossier(report: ScoreReport, matches: list[BuyerMatch]) -> str:
    """Deterministic dossier, no LLM needed."""
    c = report.company
    lines = [
        f"# {c.name}",
        "",
        f"*{c.industry} · {c.region} · founded {c.founded_year or 'unknown'} · "
        f"source: {c.source}*",
        "",
        "## Succession analysis",
        "",
        f"Succession score: **{report.total:.0f}/100**",
        "",
    ]
    for s in sorted(report.signals, key=lambda s: -report.contributions.get(s.key, 0)):
        pts = report.contributions.get(s.key, 0.0)
        lines.append(f"- ({pts:+.1f}) {s.reason}")

    lines += ["", "## Buyer shortlist", ""]
    for i, m in enumerate(matches, 1):
        lines.append(f"{i}. **{m.name}** — fit {m.fit:.0%}. {m.rationale}.")

    lines += ["", "## What the seller should know", ""]
    for note in _seller_notes():
        lines.append(f"- {note}")

    lines += [
        "",
        "## Open questions",
        "",
        "- Confirm the owner's actual age and intentions; estimates above are "
        "inferred from public records only.",
        "- Verify customer concentration, real books versus tax filings, and "
        "whether key licenses transfer.",
        "- Establish whether the company owns its land and buildings, which "
        "changes both the valuation approach and the seller's tax position.",
        "",
        "---",
        "*Generated by Succession Radar. Scores are screening aids computed "
        "from public and synthetic data; they are not statements of fact "
        "about any person's plans.*",
    ]
    return "\n".join(lines)


def llm_dossier(report: ScoreReport, matches: list[BuyerMatch],
                model: str = DEFAULT_MODEL, quiet: bool = False) -> str | None:
    """Analyst-written dossier via Claude.

    Returns None whenever the model cannot be reached, so the caller
    falls back to the template. Every failure here is non-fatal by
    design: no missing key, network problem, or API error should ever
    stop the tool from producing a dossier.
    """
    try:
        import anthropic
    except ImportError:
        if not quiet:
            print("[note] the anthropic package is not installed; writing the "
                  "template dossier. Install it with: pip install -e '.[llm]'")
        return None

    knowledge = load_knowledge()
    c = report.company
    request = DOSSIER_REQUEST.format(
        source=c.source or "unknown",
        company_json=json.dumps(dataclasses.asdict(c), ensure_ascii=False, indent=1),
        score=f"{report.total:.0f}",
        score_explanation=report.explain(),
        buyer_ranking="\n".join(f"- {m.name}: fit {m.fit:.0%} — {m.rationale}"
                                for m in matches),
    )
    try:
        # Constructing the client raises when no credentials are
        # configured, and that is not an APIError, so the whole block
        # is guarded rather than just the request.
        client = anthropic.Anthropic()
        response = client.messages.create(
            model=model,
            max_tokens=8000,
            system=[{
                "type": "text",
                "text": SYSTEM_PROMPT.format(
                    knowledge=yaml.safe_dump(knowledge, allow_unicode=True)),
                "cache_control": {"type": "ephemeral"},
            }],
            messages=[{"role": "user", "content": request}],
        )
        if response.stop_reason == "refusal":
            if not quiet:
                print("[note] the model declined this request; writing the "
                      "template dossier instead.")
            return None
        text = "".join(b.text for b in response.content if b.type == "text")
        return text or None
    except Exception as exc:  # noqa: BLE001 - never let this stop the tool
        if not quiet:
            reason = str(exc).splitlines()[0][:160]
            print(f"[note] could not reach the model ({type(exc).__name__}: "
                  f"{reason}); writing the template dossier instead.")
        return None


def build_dossier(company: Company, use_llm: bool = True) -> str:
    """Score, match, and write the dossier for one company."""
    from succession_radar.scoring.engine import score_company

    report = score_company(company)
    matches = match_buyers(company)
    if use_llm:
        text = llm_dossier(report, matches)
        if text:
            return text
    return template_dossier(report, matches)
